/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.23.3
 * source: addressbook.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace proto_test {
    export class AddressRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            areaCode?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("areaCode" in data && data.areaCode != undefined) {
                    this.areaCode = data.areaCode;
                }
            }
        }
        get areaCode() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set areaCode(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            areaCode?: number;
        }): AddressRequest {
            const message = new AddressRequest({});
            if (data.areaCode != null) {
                message.areaCode = data.areaCode;
            }
            return message;
        }
        toObject() {
            const data: {
                areaCode?: number;
            } = {};
            if (this.areaCode != null) {
                data.areaCode = this.areaCode;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.areaCode != 0)
                writer.writeInt32(1, this.areaCode);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AddressRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AddressRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.areaCode = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): AddressRequest {
            return AddressRequest.deserialize(bytes);
        }
    }
    export class Person extends pb_1.Message {
        #one_of_decls: number[][] = [[2]];
        constructor(data?: any[] | ({
            name?: string;
            id?: number;
            email?: string;
            phones?: Person.PhoneNumber[];
        } & (({
            age?: number;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [5], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("age" in data && data.age != undefined) {
                    this.age = data.age;
                }
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("email" in data && data.email != undefined) {
                    this.email = data.email;
                }
                if ("phones" in data && data.phones != undefined) {
                    this.phones = data.phones;
                }
            }
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get age() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set age(value: number) {
            pb_1.Message.setOneofField(this, 2, this.#one_of_decls[0], value);
        }
        get has_age() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get email() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set email(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get phones() {
            return pb_1.Message.getRepeatedWrapperField(this, Person.PhoneNumber, 5) as Person.PhoneNumber[];
        }
        set phones(value: Person.PhoneNumber[]) {
            pb_1.Message.setRepeatedWrapperField(this, 5, value);
        }
        get _age() {
            const cases: {
                [index: number]: "none" | "age";
            } = {
                0: "none",
                2: "age"
            };
            return cases[pb_1.Message.computeOneofCase(this, [2])];
        }
        static fromObject(data: {
            name?: string;
            age?: number;
            id?: number;
            email?: string;
            phones?: ReturnType<typeof Person.PhoneNumber.prototype.toObject>[];
        }): Person {
            const message = new Person({});
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.age != null) {
                message.age = data.age;
            }
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.email != null) {
                message.email = data.email;
            }
            if (data.phones != null) {
                message.phones = data.phones.map(item => Person.PhoneNumber.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                name?: string;
                age?: number;
                id?: number;
                email?: string;
                phones?: ReturnType<typeof Person.PhoneNumber.prototype.toObject>[];
            } = {};
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.age != null) {
                data.age = this.age;
            }
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.email != null) {
                data.email = this.email;
            }
            if (this.phones != null) {
                data.phones = this.phones.map((item: Person.PhoneNumber) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.name.length)
                writer.writeString(1, this.name);
            if (this.has_age)
                writer.writeInt32(2, this.age);
            if (this.id != 0)
                writer.writeInt32(3, this.id);
            if (this.email.length)
                writer.writeString(4, this.email);
            if (this.phones.length)
                writer.writeRepeatedMessage(5, this.phones, (item: Person.PhoneNumber) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Person {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Person();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.name = reader.readString();
                        break;
                    case 2:
                        message.age = reader.readInt32();
                        break;
                    case 3:
                        message.id = reader.readInt32();
                        break;
                    case 4:
                        message.email = reader.readString();
                        break;
                    case 5:
                        reader.readMessage(message.phones, () => pb_1.Message.addToRepeatedWrapperField(message, 5, Person.PhoneNumber.deserialize(reader), Person.PhoneNumber));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Person {
            return Person.deserialize(bytes);
        }
    }
    export namespace Person {
        export enum PhoneType {
            MOBILE = 0,
            HOME = 1,
            WORK = 2
        }
        export class PhoneNumber extends pb_1.Message {
            #one_of_decls: number[][] = [];
            constructor(data?: any[] | {
                number?: string;
                type?: Person.PhoneType;
            }) {
                super();
                pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
                if (!Array.isArray(data) && typeof data == "object") {
                    if ("number" in data && data.number != undefined) {
                        this.number = data.number;
                    }
                    if ("type" in data && data.type != undefined) {
                        this.type = data.type;
                    }
                }
            }
            get number() {
                return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
            }
            set number(value: string) {
                pb_1.Message.setField(this, 1, value);
            }
            get type() {
                return pb_1.Message.getFieldWithDefault(this, 2, Person.PhoneType.MOBILE) as Person.PhoneType;
            }
            set type(value: Person.PhoneType) {
                pb_1.Message.setField(this, 2, value);
            }
            static fromObject(data: {
                number?: string;
                type?: Person.PhoneType;
            }): PhoneNumber {
                const message = new PhoneNumber({});
                if (data.number != null) {
                    message.number = data.number;
                }
                if (data.type != null) {
                    message.type = data.type;
                }
                return message;
            }
            toObject() {
                const data: {
                    number?: string;
                    type?: Person.PhoneType;
                } = {};
                if (this.number != null) {
                    data.number = this.number;
                }
                if (this.type != null) {
                    data.type = this.type;
                }
                return data;
            }
            serialize(): Uint8Array;
            serialize(w: pb_1.BinaryWriter): void;
            serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
                const writer = w || new pb_1.BinaryWriter();
                if (this.number.length)
                    writer.writeString(1, this.number);
                if (this.type != Person.PhoneType.MOBILE)
                    writer.writeEnum(2, this.type);
                if (!w)
                    return writer.getResultBuffer();
            }
            static deserialize(bytes: Uint8Array | pb_1.BinaryReader): PhoneNumber {
                const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PhoneNumber();
                while (reader.nextField()) {
                    if (reader.isEndGroup())
                        break;
                    switch (reader.getFieldNumber()) {
                        case 1:
                            message.number = reader.readString();
                            break;
                        case 2:
                            message.type = reader.readEnum();
                            break;
                        default: reader.skipField();
                    }
                }
                return message;
            }
            serializeBinary(): Uint8Array {
                return this.serialize();
            }
            static deserializeBinary(bytes: Uint8Array): PhoneNumber {
                return PhoneNumber.deserialize(bytes);
            }
        }
    }
    export class AddressBook extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            areaCode?: number;
            people?: Person[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [2], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("areaCode" in data && data.areaCode != undefined) {
                    this.areaCode = data.areaCode;
                }
                if ("people" in data && data.people != undefined) {
                    this.people = data.people;
                }
            }
        }
        get areaCode() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set areaCode(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get people() {
            return pb_1.Message.getRepeatedWrapperField(this, Person, 2) as Person[];
        }
        set people(value: Person[]) {
            pb_1.Message.setRepeatedWrapperField(this, 2, value);
        }
        static fromObject(data: {
            areaCode?: number;
            people?: ReturnType<typeof Person.prototype.toObject>[];
        }): AddressBook {
            const message = new AddressBook({});
            if (data.areaCode != null) {
                message.areaCode = data.areaCode;
            }
            if (data.people != null) {
                message.people = data.people.map(item => Person.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                areaCode?: number;
                people?: ReturnType<typeof Person.prototype.toObject>[];
            } = {};
            if (this.areaCode != null) {
                data.areaCode = this.areaCode;
            }
            if (this.people != null) {
                data.people = this.people.map((item: Person) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.areaCode != 0)
                writer.writeInt32(1, this.areaCode);
            if (this.people.length)
                writer.writeRepeatedMessage(2, this.people, (item: Person) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): AddressBook {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AddressBook();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.areaCode = reader.readInt32();
                        break;
                    case 2:
                        reader.readMessage(message.people, () => pb_1.Message.addToRepeatedWrapperField(message, 2, Person.deserialize(reader), Person));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): AddressBook {
            return AddressBook.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedFetchAddressService {
        static definition = {
            GetAddress: {
                path: "/proto_test.FetchAddress/GetAddress",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: AddressRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => AddressRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: AddressBook) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => AddressBook.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract GetAddress(call: grpc_1.ServerUnaryCall<AddressRequest, AddressBook>, callback: grpc_1.sendUnaryData<AddressBook>): void;
    }
    export class FetchAddressClient extends grpc_1.makeGenericClientConstructor(UnimplementedFetchAddressService.definition, "FetchAddress", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        GetAddress: GrpcUnaryServiceInterface<AddressRequest, AddressBook> = (message: AddressRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<AddressBook>, options?: grpc_1.CallOptions | grpc_1.requestCallback<AddressBook>, callback?: grpc_1.requestCallback<AddressBook>): grpc_1.ClientUnaryCall => {
            return super.GetAddress(message, metadata, options, callback);
        };
    }
}
