# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addons.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x64\x64ons.proto\x12\x07\x63odegen\"H\n\x10\x41\x64\x64\x41\x64\x64onsRequest\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12\x1e\n\x06\x61\x64\x64ons\x18\x02 \x03(\x0b\x32\x0e.codegen.Addon\"o\n\x05\x41\x64\x64on\x12\'\n\nack_add_on\x18\x01 \x01(\x0b\x32\x11.codegen.AckAddOnH\x00\x12\x34\n\x11kube_proxy_add_on\x18\x02 \x01(\x0b\x32\x17.codegen.KubeProxyAddOnH\x00\x42\x07\n\x05\x61\x64\x64on\"Q\n\x12\x41\x64\x64\x41\x63kAddOnRequest\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12%\n\nack_add_on\x18\x02 \x01(\x0b\x32\x11.codegen.AckAddOn\"7\n\x08\x41\x63kAddOn\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x0bserviceName\x18\x02 \x01(\tB\x05\n\x03_id\"d\n\x18\x41\x64\x64KubeProxyAddOnRequest\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12\x32\n\x11kube_proxy_add_on\x18\x02 \x01(\x0b\x32\x17.codegen.KubeProxyAddOn\"2\n\x0eKubeProxyAddOn\x12\x14\n\x07version\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_version\"^\n\x16\x41\x64\x64\x43oreDNSAddOnRequest\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12.\n\x0f\x63ore_dns_add_on\x18\x02 \x01(\x0b\x32\x15.codegen.CoreDNSAddOn\"0\n\x0c\x43oreDNSAddOn\x12\x14\n\x07version\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_version\"F\n\x12MetricsServerAddOn\x12\x1c\n\x0f\x63reateNamespace\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x12\n\x10_createNamespace\"p\n\x1c\x41\x64\x64MetricsServerAddOnRequest\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12:\n\x15metrics_server_add_on\x18\x02 \x01(\x0b\x32\x1b.codegen.MetricsServerAddOnB(Z&github.com/zjaco13/sdks/go-sdk/codegenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addons_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z&github.com/zjaco13/sdks/go-sdk/codegen'
  _globals['_ADDADDONSREQUEST']._serialized_start=25
  _globals['_ADDADDONSREQUEST']._serialized_end=97
  _globals['_ADDON']._serialized_start=99
  _globals['_ADDON']._serialized_end=210
  _globals['_ADDACKADDONREQUEST']._serialized_start=212
  _globals['_ADDACKADDONREQUEST']._serialized_end=293
  _globals['_ACKADDON']._serialized_start=295
  _globals['_ACKADDON']._serialized_end=350
  _globals['_ADDKUBEPROXYADDONREQUEST']._serialized_start=352
  _globals['_ADDKUBEPROXYADDONREQUEST']._serialized_end=452
  _globals['_KUBEPROXYADDON']._serialized_start=454
  _globals['_KUBEPROXYADDON']._serialized_end=504
  _globals['_ADDCOREDNSADDONREQUEST']._serialized_start=506
  _globals['_ADDCOREDNSADDONREQUEST']._serialized_end=600
  _globals['_COREDNSADDON']._serialized_start=602
  _globals['_COREDNSADDON']._serialized_end=650
  _globals['_METRICSSERVERADDON']._serialized_start=652
  _globals['_METRICSSERVERADDON']._serialized_end=722
  _globals['_ADDMETRICSSERVERADDONREQUEST']._serialized_start=724
  _globals['_ADDMETRICSSERVERADDONREQUEST']._serialized_end=836
# @@protoc_insertion_point(module_scope)
