# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster_providers.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63luster_providers.proto\x12\x07\x63odegen\"e\n\x19\x41\x64\x64\x43lusterProviderRequest\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12\x32\n\x10\x63luster_provider\x18\x02 \x01(\x0b\x32\x18.codegen.ClusterProvider\"\x9f\x01\n\x0f\x43lusterProvider\x12;\n\x14\x61sg_cluster_provider\x18\x01 \x01(\x0b\x32\x1b.codegen.AsgClusterProviderH\x00\x12;\n\x14mng_cluster_provider\x18\x02 \x01(\x0b\x32\x1b.codegen.MngClusterProviderH\x00\x42\x12\n\x10\x63luster_provider\"o\n\x1c\x41\x64\x64\x41sgClusterProviderRequest\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12\x39\n\x14\x61sg_cluster_provider\x18\x02 \x01(\x0b\x32\x1b.codegen.AsgClusterProvider\"M\n\x12\x41sgClusterProvider\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\tB\x07\n\x05_name\"o\n\x1c\x41\x64\x64MngClusterProviderRequest\x12\x14\n\x0c\x63luster_name\x18\x01 \x01(\t\x12\x39\n\x14mng_cluster_provider\x18\x02 \x01(\x0b\x32\x1b.codegen.MngClusterProvider\"A\n\x12MngClusterProvider\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x07version\x18\x02 \x01(\tB\x07\n\x05_nameB(Z&github.com/zjaco13/sdks/go-sdk/codegenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cluster_providers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z&github.com/zjaco13/sdks/go-sdk/codegen'
  _globals['_ADDCLUSTERPROVIDERREQUEST']._serialized_start=36
  _globals['_ADDCLUSTERPROVIDERREQUEST']._serialized_end=137
  _globals['_CLUSTERPROVIDER']._serialized_start=140
  _globals['_CLUSTERPROVIDER']._serialized_end=299
  _globals['_ADDASGCLUSTERPROVIDERREQUEST']._serialized_start=301
  _globals['_ADDASGCLUSTERPROVIDERREQUEST']._serialized_end=412
  _globals['_ASGCLUSTERPROVIDER']._serialized_start=414
  _globals['_ASGCLUSTERPROVIDER']._serialized_end=491
  _globals['_ADDMNGCLUSTERPROVIDERREQUEST']._serialized_start=493
  _globals['_ADDMNGCLUSTERPROVIDERREQUEST']._serialized_end=604
  _globals['_MNGCLUSTERPROVIDER']._serialized_start=606
  _globals['_MNGCLUSTERPROVIDER']._serialized_end=671
# @@protoc_insertion_point(module_scope)
