# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import addressbook_pb2 as addressbook__pb2


class FetchAddressStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAddress = channel.unary_unary(
                '/proto_test.FetchAddress/GetAddress',
                request_serializer=addressbook__pb2.AddressRequest.SerializeToString,
                response_deserializer=addressbook__pb2.AddressBook.FromString,
                )


class FetchAddressServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FetchAddressServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddress,
                    request_deserializer=addressbook__pb2.AddressRequest.FromString,
                    response_serializer=addressbook__pb2.AddressBook.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto_test.FetchAddress', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FetchAddress(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto_test.FetchAddress/GetAddress',
            addressbook__pb2.AddressRequest.SerializeToString,
            addressbook__pb2.AddressBook.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
