# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcluster.proto\x12\nproto_test\"6\n\x0c\x45ksBlueprint\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\"$\n\x14\x45ksBlueprintResponse\x12\x0c\n\x04resp\x18\x01 \x01(\t2]\n\x0e\x43lusterService\x12K\n\x0bSendCluster\x12\x18.proto_test.EksBlueprint\x1a .proto_test.EksBlueprintResponse\"\x00\x42*Z(github.com/zjaco13/proto-test/go/codegenb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cluster_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z(github.com/zjaco13/proto-test/go/codegen'
  _globals['_EKSBLUEPRINT']._serialized_start=29
  _globals['_EKSBLUEPRINT']._serialized_end=83
  _globals['_EKSBLUEPRINTRESPONSE']._serialized_start=85
  _globals['_EKSBLUEPRINTRESPONSE']._serialized_end=121
  _globals['_CLUSTERSERVICE']._serialized_start=123
  _globals['_CLUSTERSERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
