# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addons.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x64\x64ons.proto\x12\x05proto\"0\n\x10\x41\x64\x64\x41\x64\x64onsRequest\x12\x1c\n\x06\x61\x64\x64ons\x18\x01 \x03(\x0b\x32\x0c.proto.Addon\"7\n\x05\x41\x64\x64on\x12%\n\nack_add_on\x18\x01 \x01(\x0b\x32\x0f.proto.AckAddOnH\x00\x42\x07\n\x05\x61\x64\x64on\"7\n\x08\x41\x63kAddOn\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x0bserviceName\x18\x02 \x01(\tB\x05\n\x03_idB1Z/github.com/zjaco13/proto-test/sdks/go-sdk/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addons_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/zjaco13/proto-test/sdks/go-sdk/proto'
  _globals['_ADDADDONSREQUEST']._serialized_start=23
  _globals['_ADDADDONSREQUEST']._serialized_end=71
  _globals['_ADDON']._serialized_start=73
  _globals['_ADDON']._serialized_end=128
  _globals['_ACKADDON']._serialized_start=130
  _globals['_ACKADDON']._serialized_end=185
# @@protoc_insertion_point(module_scope)
