# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import team_pb2 as team__pb2
import cluster_provider_pb2 as cluster__provider__pb2
import resource_provider_pb2 as resource__provider__pb2
import addons_pb2 as addons__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcluster.proto\x12\x05proto\x1a\nteam.proto\x1a\x16\x63luster_provider.proto\x1a\x17resource_provider.proto\x1a\x0c\x61\x64\x64ons.proto\"\x1e\n\x0b\x41PIResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\">\n\x14\x43reateClusterRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\"l\n\x13\x42uildClusterRequest\x12\x13\n\x0b\x63lusterName\x18\x01 \x01(\t\x12\x14\n\x07\x61\x63\x63ount\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06region\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\n\n\x08_accountB\t\n\x07_region2\x9e\x03\n\x0e\x43lusterService\x12@\n\rCreateCluster\x12\x1b.proto.CreateClusterRequest\x1a\x12.proto.APIResponse\x12\x36\n\x08\x41\x64\x64Teams\x12\x16.proto.AddTeamsRequest\x1a\x12.proto.APIResponse\x12J\n\x12\x41\x64\x64\x43lusterProvider\x12 .proto.AddClusterProviderRequest\x1a\x12.proto.APIResponse\x12L\n\x13\x41\x64\x64ResourceProvider\x12!.proto.AddResourceProviderRequest\x1a\x12.proto.APIResponse\x12\x38\n\tAddAddons\x12\x17.proto.AddAddonsRequest\x1a\x12.proto.APIResponse\x12>\n\x0c\x42uildCluster\x12\x1a.proto.BuildClusterRequest\x1a\x12.proto.APIResponseB1Z/github.com/zjaco13/proto-test/sdks/go-sdk/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cluster_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/zjaco13/proto-test/sdks/go-sdk/proto'
  _globals['_APIRESPONSE']._serialized_start=99
  _globals['_APIRESPONSE']._serialized_end=129
  _globals['_CREATECLUSTERREQUEST']._serialized_start=131
  _globals['_CREATECLUSTERREQUEST']._serialized_end=193
  _globals['_BUILDCLUSTERREQUEST']._serialized_start=195
  _globals['_BUILDCLUSTERREQUEST']._serialized_end=303
  _globals['_CLUSTERSERVICE']._serialized_start=306
  _globals['_CLUSTERSERVICE']._serialized_end=720
# @@protoc_insertion_point(module_scope)
