# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resource_provider.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17resource_provider.proto\x12\x05proto\"^\n\x1a\x41\x64\x64ResourceProviderRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x32\n\x11resource_provider\x18\x02 \x01(\x0b\x32\x17.proto.ResourceProvider\"S\n\x10ResourceProvider\x12*\n\x0cvpc_provider\x18\x01 \x01(\x0b\x32\x12.proto.VpcProviderH\x00\x42\x13\n\x11resource_provider\"+\n\x0bVpcProvider\x12\x12\n\x05vpcId\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_vpcIdB1Z/github.com/zjaco13/proto-test/sdks/go-sdk/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource_provider_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/zjaco13/proto-test/sdks/go-sdk/proto'
  _globals['_ADDRESOURCEPROVIDERREQUEST']._serialized_start=34
  _globals['_ADDRESOURCEPROVIDERREQUEST']._serialized_end=128
  _globals['_RESOURCEPROVIDER']._serialized_start=130
  _globals['_RESOURCEPROVIDER']._serialized_end=213
  _globals['_VPCPROVIDER']._serialized_start=215
  _globals['_VPCPROVIDER']._serialized_end=258
# @@protoc_insertion_point(module_scope)
