# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: team.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nteam.proto\x12\x05proto\"-\n\x0f\x41\x64\x64TeamsRequest\x12\x1a\n\x05teams\x18\x01 \x03(\x0b\x32\x0b.proto.Team\"\x9c\x01\n\x04Team\x12*\n\x0cgeneric_team\x18\x01 \x01(\x0b\x32\x12.proto.GenericTeamH\x00\x12,\n\rplatform_team\x18\x02 \x01(\x0b\x32\x13.proto.PlatformTeamH\x00\x12\x32\n\x10\x61pplication_team\x18\x03 \x01(\x0b\x32\x16.proto.ApplicationTeamH\x00\x42\x06\n\x04team\"\x1b\n\x0bGenericTeam\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0cPlatformTeam\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x0f\x41pplicationTeam\x12\x0c\n\x04name\x18\x01 \x01(\tB1Z/github.com/zjaco13/proto-test/sdks/go-sdk/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'team_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/zjaco13/proto-test/sdks/go-sdk/proto'
  _globals['_ADDTEAMSREQUEST']._serialized_start=21
  _globals['_ADDTEAMSREQUEST']._serialized_end=66
  _globals['_TEAM']._serialized_start=69
  _globals['_TEAM']._serialized_end=225
  _globals['_GENERICTEAM']._serialized_start=227
  _globals['_GENERICTEAM']._serialized_end=254
  _globals['_PLATFORMTEAM']._serialized_start=256
  _globals['_PLATFORMTEAM']._serialized_end=284
  _globals['_APPLICATIONTEAM']._serialized_start=286
  _globals['_APPLICATIONTEAM']._serialized_end=317
# @@protoc_insertion_point(module_scope)
