// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: resource_provider.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddResourceProviderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ResourceProvider *ResourceProvider `protobuf:"bytes,2,opt,name=resource_provider,json=resourceProvider,proto3" json:"resource_provider,omitempty"`
}

func (x *AddResourceProviderRequest) Reset() {
	*x = AddResourceProviderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_provider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddResourceProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResourceProviderRequest) ProtoMessage() {}

func (x *AddResourceProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResourceProviderRequest.ProtoReflect.Descriptor instead.
func (*AddResourceProviderRequest) Descriptor() ([]byte, []int) {
	return file_resource_provider_proto_rawDescGZIP(), []int{0}
}

func (x *AddResourceProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddResourceProviderRequest) GetResourceProvider() *ResourceProvider {
	if x != nil {
		return x.ResourceProvider
	}
	return nil
}

type ResourceProvider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ResourceProvider:
	//
	//	*ResourceProvider_VpcProvider
	ResourceProvider isResourceProvider_ResourceProvider `protobuf_oneof:"resource_provider"`
}

func (x *ResourceProvider) Reset() {
	*x = ResourceProvider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_provider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceProvider) ProtoMessage() {}

func (x *ResourceProvider) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceProvider.ProtoReflect.Descriptor instead.
func (*ResourceProvider) Descriptor() ([]byte, []int) {
	return file_resource_provider_proto_rawDescGZIP(), []int{1}
}

func (m *ResourceProvider) GetResourceProvider() isResourceProvider_ResourceProvider {
	if m != nil {
		return m.ResourceProvider
	}
	return nil
}

func (x *ResourceProvider) GetVpcProvider() *VpcProvider {
	if x, ok := x.GetResourceProvider().(*ResourceProvider_VpcProvider); ok {
		return x.VpcProvider
	}
	return nil
}

type isResourceProvider_ResourceProvider interface {
	isResourceProvider_ResourceProvider()
}

type ResourceProvider_VpcProvider struct {
	VpcProvider *VpcProvider `protobuf:"bytes,1,opt,name=vpc_provider,json=vpcProvider,proto3,oneof"`
}

func (*ResourceProvider_VpcProvider) isResourceProvider_ResourceProvider() {}

type VpcProvider struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpcId *string `protobuf:"bytes,1,opt,name=vpcId,proto3,oneof" json:"vpcId,omitempty"`
}

func (x *VpcProvider) Reset() {
	*x = VpcProvider{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_provider_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VpcProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpcProvider) ProtoMessage() {}

func (x *VpcProvider) ProtoReflect() protoreflect.Message {
	mi := &file_resource_provider_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpcProvider.ProtoReflect.Descriptor instead.
func (*VpcProvider) Descriptor() ([]byte, []int) {
	return file_resource_provider_proto_rawDescGZIP(), []int{2}
}

func (x *VpcProvider) GetVpcId() string {
	if x != nil && x.VpcId != nil {
		return *x.VpcId
	}
	return ""
}

var File_resource_provider_proto protoreflect.FileDescriptor

var file_resource_provider_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x76, 0x0a, 0x1a, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x44, 0x0a, 0x11, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x10, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x60, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x0c,
	0x76, 0x70, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x70, 0x63, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x76, 0x70, 0x63, 0x50, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x42, 0x13, 0x0a, 0x11, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x0b, 0x56, 0x70,
	0x63, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x70, 0x63,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x76, 0x70, 0x63, 0x49,
	0x64, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x70, 0x63, 0x49, 0x64, 0x42, 0x31,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x6a, 0x61,
	0x63, 0x6f, 0x31, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2f,
	0x73, 0x64, 0x6b, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resource_provider_proto_rawDescOnce sync.Once
	file_resource_provider_proto_rawDescData = file_resource_provider_proto_rawDesc
)

func file_resource_provider_proto_rawDescGZIP() []byte {
	file_resource_provider_proto_rawDescOnce.Do(func() {
		file_resource_provider_proto_rawDescData = protoimpl.X.CompressGZIP(file_resource_provider_proto_rawDescData)
	})
	return file_resource_provider_proto_rawDescData
}

var file_resource_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_resource_provider_proto_goTypes = []interface{}{
	(*AddResourceProviderRequest)(nil), // 0: proto.AddResourceProviderRequest
	(*ResourceProvider)(nil),           // 1: proto.ResourceProvider
	(*VpcProvider)(nil),                // 2: proto.VpcProvider
}
var file_resource_provider_proto_depIdxs = []int32{
	1, // 0: proto.AddResourceProviderRequest.resource_provider:type_name -> proto.ResourceProvider
	2, // 1: proto.ResourceProvider.vpc_provider:type_name -> proto.VpcProvider
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_resource_provider_proto_init() }
func file_resource_provider_proto_init() {
	if File_resource_provider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resource_provider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddResourceProviderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resource_provider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceProvider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resource_provider_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VpcProvider); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_resource_provider_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ResourceProvider_VpcProvider)(nil),
	}
	file_resource_provider_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resource_provider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_provider_proto_goTypes,
		DependencyIndexes: file_resource_provider_proto_depIdxs,
		MessageInfos:      file_resource_provider_proto_msgTypes,
	}.Build()
	File_resource_provider_proto = out.File
	file_resource_provider_proto_rawDesc = nil
	file_resource_provider_proto_goTypes = nil
	file_resource_provider_proto_depIdxs = nil
}
